export  const cartCollection = 'carts'
export const  productCollection = 'products'
export const messageCollection = 'messages'
export const userCollection = 'users'
export const tickeCollection = 'tickets'